// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

use crate::ffi;

glib::wrapper! {
    #[doc(alias = "GstGLBaseMixerPad")]
    pub struct GLBaseMixerPad(Object<ffi::GstGLBaseMixerPad, ffi::GstGLBaseMixerPadClass>) @extends gst_video::VideoAggregatorPad, gst_base::AggregatorPad, gst::Pad, gst::Object;

    match fn {
        type_ => || ffi::gst_gl_base_mixer_pad_get_type(),
    }
}

impl GLBaseMixerPad {
    pub const NONE: Option<&'static GLBaseMixerPad> = None;
}

unsafe impl Send for GLBaseMixerPad {}
unsafe impl Sync for GLBaseMixerPad {}
