// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

use crate::{ffi, GLContext};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "GstGLBaseMixer")]
    pub struct GLBaseMixer(Object<ffi::GstGLBaseMixer, ffi::GstGLBaseMixerClass>) @extends gst_video::VideoAggregator, gst_base::Aggregator, gst::Element, gst::Object;

    match fn {
        type_ => || ffi::gst_gl_base_mixer_get_type(),
    }
}

impl GLBaseMixer {
    pub const NONE: Option<&'static GLBaseMixer> = None;
}

unsafe impl Send for GLBaseMixer {}
unsafe impl Sync for GLBaseMixer {}

pub trait GLBaseMixerExt: IsA<GLBaseMixer> + 'static {
    #[doc(alias = "gst_gl_base_mixer_get_gl_context")]
    #[doc(alias = "get_gl_context")]
    fn gl_context(&self) -> Option<GLContext> {
        unsafe {
            from_glib_full(ffi::gst_gl_base_mixer_get_gl_context(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[cfg(feature = "v1_24")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_24")))]
    fn context(&self) -> Option<GLContext> {
        ObjectExt::property(self.as_ref(), "context")
    }

    #[cfg(feature = "v1_24")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_24")))]
    #[doc(alias = "context")]
    fn connect_context_notify<F: Fn(&Self) + Send + Sync + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_context_trampoline<
            P: IsA<GLBaseMixer>,
            F: Fn(&P) + Send + Sync + 'static,
        >(
            this: *mut ffi::GstGLBaseMixer,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(GLBaseMixer::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::context".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_context_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<GLBaseMixer>> GLBaseMixerExt for O {}
