// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

use crate::{ffi, GLBaseMixerPad};

glib::wrapper! {
    #[doc(alias = "GstGLMixerPad")]
    pub struct GLMixerPad(Object<ffi::GstGLMixerPad, ffi::GstGLMixerPadClass>) @extends GLBaseMixerPad, gst_video::VideoAggregatorPad, gst_base::AggregatorPad, gst::Pad, gst::Object;

    match fn {
        type_ => || ffi::gst_gl_mixer_pad_get_type(),
    }
}

impl GLMixerPad {
    pub const NONE: Option<&'static GLMixerPad> = None;
}

unsafe impl Send for GLMixerPad {}
unsafe impl Sync for GLMixerPad {}
