// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

use crate::{ffi, GLBaseMixer, GLFramebuffer};
use glib::{prelude::*, translate::*};

glib::wrapper! {
    #[doc(alias = "GstGLMixer")]
    pub struct GLMixer(Object<ffi::GstGLMixer, ffi::GstGLMixerClass>) @extends GLBaseMixer, gst_video::VideoAggregator, gst_base::Aggregator, gst::Element, gst::Object;

    match fn {
        type_ => || ffi::gst_gl_mixer_get_type(),
    }
}

impl GLMixer {
    pub const NONE: Option<&'static GLMixer> = None;
}

unsafe impl Send for GLMixer {}
unsafe impl Sync for GLMixer {}

pub trait GLMixerExt: IsA<GLMixer> + 'static {
    #[doc(alias = "gst_gl_mixer_get_framebuffer")]
    #[doc(alias = "get_framebuffer")]
    fn framebuffer(&self) -> GLFramebuffer {
        unsafe {
            from_glib_full(ffi::gst_gl_mixer_get_framebuffer(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "gst_gl_mixer_process_textures")]
    fn process_textures(&self, outbuf: &gst::Buffer) -> bool {
        unsafe {
            from_glib(ffi::gst_gl_mixer_process_textures(
                self.as_ref().to_glib_none().0,
                outbuf.to_glib_none().0,
            ))
        }
    }
}

impl<O: IsA<GLMixer>> GLMixerExt for O {}
